"""Generate HTML reports for batch QA results."""
from pathlib import Path
from typing import Optional
from .analyzer import QualityReport
from .comparison import ComparisonResult


def generate_report(
    reports: list[QualityReport],
    title: str = "Batch QA Report",
    output_path: str = "qa_report.html",
) -> str:
    """Generate a visual HTML report from quality analysis results."""
    sorted_reports = sorted(reports, key=lambda r: r.overall_score, reverse=True)
    total = len(reports)
    flagged = sum(1 for r in reports if r.issues)

    # Build rows
    rows_html = ""
    for i, r in enumerate(reports):
        status = "🔴" if r.issues else "🟢"
        issues_str = ", ".join(r.issues) if r.issues else "—"
        rows_html += f"""
        <tr class="{'issue' if r.issues else 'ok'}">
            <td>{i + 1}</td>
            <td><img src="{r.path}" class="thumb" onerror="this.style.display='none'"></td>
            <td class="mono">{r.filename}</td>
            <td>{r.width}×{r.height}</td>
            <td>{r.megapixels} MP</td>
            <td>{r.file_size_kb} KB</td>
            <td class="score">{r.overall_score}</td>
            <td class="score">{r.sharpness}</td>
            <td class="score">{r.brightness:.0f}</td>
            <td class="score">{r.contrast:.0f}</td>
            <td class="score">{r.noise_level:.0f}</td>
            <td>{status}</td>
            <td class="issues">{issues_str}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }}
    h1 {{ color: #58a6ff; margin-bottom: 8px; }}
    .subtitle {{ color: #8b949e; margin-bottom: 24px; }}
    .stats {{ display: flex; gap: 16px; margin-bottom: 24px; }}
    .stat {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; min-width: 140px; }}
    .stat .num {{ font-size: 28px; font-weight: bold; color: #58a6ff; }}
    .stat .label {{ color: #8b949e; font-size: 13px; margin-top: 4px; }}
    table {{ width: 100%; border-collapse: collapse; background: #161b22; border: 1px solid #30363d; border-radius: 8px; overflow: hidden; }}
    th {{ background: #21262d; color: #8b949e; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
    td {{ padding: 8px 12px; border-top: 1px solid #21262d; font-size: 13px; }}
    tr.ok td {{ }}
    tr.issue td {{ background: #1c1208; }}
    tr.issue:hover td {{ background: #2a1f10; }}
    .thumb {{ width: 48px; height: 48px; object-fit: cover; border-radius: 4px; }}
    .mono {{ font-family: 'SF Mono', Consolas, monospace; font-size: 12px; }}
    .score {{ font-weight: bold; color: #58a6ff; }}
    .issues {{ color: #f0883e; font-size: 12px; }}
    .bar {{ height: 6px; border-radius: 3px; background: #21262d; overflow: hidden; }}
    .bar-fill {{ height: 100%; border-radius: 3px; }}
</style>
</head>
<body>
<h1>📊 {title}</h1>
<p class="subtitle">Generated by ai-batch-qa</p>

<div class="stats">
    <div class="stat"><div class="num">{total}</div><div class="label">Total Images</div></div>
    <div class="stat"><div class="num">{total - flagged}</div><div class="label">Passed</div></div>
    <div class="stat"><div class="num">{flagged}</div><div class="label">Flagged</div></div>
    <div class="stat"><div class="num">{sorted_reports[0].overall_score if sorted_reports else 0}</div><div class="label">Best Score</div></div>
    <div class="stat"><div class="num">{sorted_reports[-1].overall_score if sorted_reports else 0}</div><div class="label">Worst Score</div></div>
</div>

<table>
<thead>
<tr>
    <th>#</th><th>Preview</th><th>Filename</th><th>Size</th><th>Mp</th>
    <th>File KB</th><th>Score</th><th>Sharp</th><th>Bright</th>
    <th>Contrast</th><th>Noise</th><th>Status</th><th>Issues</th>
</tr>
</thead>
<tbody>
{rows_html}
</tbody>
</table>
</body>
</html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    return output_path


def generate_comparison_report(
    results: list[ComparisonResult],
    title: str = "A/B Comparison Report",
    output_path: str = "comparison_report.html",
) -> str:
    """Generate an HTML comparison report."""
    cards = ""
    for r in results:
        metrics_html = ""
        for metric, data in r.metric_comparison.items():
            a_bar = min(100, data["a"] / 100 * 100) if metric != "brightness" else data["a"] / 255 * 100
            b_bar = min(100, data["b"] / 100 * 100) if metric != "brightness" else data["b"] / 255 * 100
            winner_a = "🏆" if data["winner"] == "a" else ""
            winner_b = "🏆" if data["winner"] == "b" else ""
            metrics_html += f"""
            <div class="metric">
                <span class="metric-name">{metric}</span>
                <div class="metric-vals">
                    <span>{data['a']:.1f} {winner_a}</span>
                    <span>{data['b']:.1f} {winner_b}</span>
                </div>
            </div>"""

        winner_text = f"Winner: Image {'A' if r.winner == 'a' else 'B' if r.winner == 'b' else 'Tie'}"
        cards += f"""
        <div class="card">
            <div class="card-header">{r.image_a.filename} vs {r.image_b.filename}</div>
            <div class="winner {'win-a' if r.winner == 'a' else 'win-b' if r.winner == 'b' else 'tie'}">{winner_text} (diff: {r.score_diff})</div>
            <div class="metrics">{metrics_html}</div>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
    body {{ font-family: -apple-system, sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }}
    h1 {{ color: #58a6ff; }}
    .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; margin-bottom: 16px; }}
    .card-header {{ font-weight: bold; margin-bottom: 8px; }}
    .winner {{ padding: 8px; border-radius: 4px; margin-bottom: 12px; font-weight: bold; }}
    .win-a {{ background: #0f291a; color: #3fb950; }}
    .win-b {{ background: #0f291a; color: #3fb950; }}
    .tie {{ background: #1c1c24; color: #8b949e; }}
    .metric {{ display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px solid #21262d; }}
    .metric-name {{ color: #8b949e; }}
    .metric-vals {{ display: flex; gap: 24px; }}
</style>
</head>
<body>
<h1>⚖️ {title}</h1>
<p style="color:#8b949e; margin-bottom: 24px;">Generated by ai-batch-qa</p>
{cards}
</body>
</html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    return output_path
